/**
 * NOTE: This class is auto generated by the swagger code generator program (3.0.36).
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */
package io.swagger.api;

import io.swagger.model.Specification;
import io.swagger.v3.oas.annotations.Operation;
import io.swagger.v3.oas.annotations.Parameter;
import io.swagger.v3.oas.annotations.enums.ParameterIn;
import io.swagger.v3.oas.annotations.responses.ApiResponses;
import io.swagger.v3.oas.annotations.responses.ApiResponse;
import io.swagger.v3.oas.annotations.media.ArraySchema;
import io.swagger.v3.oas.annotations.media.Content;
import io.swagger.v3.oas.annotations.media.Schema;
import io.swagger.v3.oas.annotations.security.SecurityRequirement;
import org.springframework.http.ResponseEntity;
import org.springframework.validation.annotation.Validated;
import org.springframework.web.bind.annotation.PathVariable;
import org.springframework.web.bind.annotation.RequestBody;
import org.springframework.web.bind.annotation.RequestHeader;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RequestMethod;
import org.springframework.web.bind.annotation.RequestParam;
import org.springframework.web.bind.annotation.RequestPart;
import org.springframework.web.multipart.MultipartFile;
import org.springframework.web.bind.annotation.CookieValue;

import javax.validation.Valid;
import javax.validation.constraints.*;
import java.util.List;
import java.util.Map;

@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.SpringCodegen", date = "2022-12-15T15:11:33.384Z[GMT]")
@Validated
public interface SpecificationApi {

    @Operation(summary = "Delete specification by ID", description = "This delete specification by ID.", tags={ "VDS specification" })
    @ApiResponses(value = { 
        @ApiResponse(responseCode = "200", description = "successful operation", content = @Content(mediaType = "application/json", schema = @Schema(implementation = Specification.class))),
        
        @ApiResponse(responseCode = "400", description = "Invalid specification ID supplied"),
        
        @ApiResponse(responseCode = "404", description = "Specification not foun") })
    @RequestMapping(value = "/specification/{specID}",
        produces = { "application/json", "application/xml" }, 
        method = RequestMethod.DELETE)
    ResponseEntity<Specification> deleteSpec(@Parameter(in = ParameterIn.PATH, description = "The specification ID that needs to be deleted", required=true, schema=@Schema()) @PathVariable("specID") Long specID);


    @Operation(summary = "Get all VDS specifications info", description = "Get all VDS specifications info", tags={ "VDS specification" })
    @ApiResponses(value = { 
        @ApiResponse(responseCode = "200", description = "Successful operation", content = @Content(mediaType = "application/json", array = @ArraySchema(schema = @Schema(implementation = Specification.class)))),
        
        @ApiResponse(responseCode = "405", description = "Invalid input") })
    @RequestMapping(value = "/specification/all",
        produces = { "application/json", "application/xml" }, 
        method = RequestMethod.GET)
    ResponseEntity<List<Specification>> getAllVDS();


    @Operation(summary = "Get VDS specification info by ID", description = "Get VDS specification info by ID", tags={ "VDS specification" })
    @ApiResponses(value = { 
        @ApiResponse(responseCode = "200", description = "successful operation", content = @Content(mediaType = "application/json", schema = @Schema(implementation = Specification.class))),
        
        @ApiResponse(responseCode = "400", description = "Invalid specification ID supplied"),
        
        @ApiResponse(responseCode = "404", description = "Specification not found") })
    @RequestMapping(value = "/specification/{specID}",
        produces = { "application/json", "application/xml" }, 
        method = RequestMethod.GET)
    ResponseEntity<Specification> getSpec(@Parameter(in = ParameterIn.PATH, description = "", required=true, schema=@Schema()) @PathVariable("specID") Long specID);


    @Operation(summary = "Update VDS specification info by ID", description = "Update VDS specification info by ID", tags={ "VDS specification" })
    @ApiResponses(value = { 
        @ApiResponse(responseCode = "200", description = "successful operation", content = @Content(mediaType = "application/json", schema = @Schema(implementation = Specification.class))),
        
        @ApiResponse(responseCode = "400", description = "Invalid specification ID supplied"),
        
        @ApiResponse(responseCode = "404", description = "Specification not found") })
    @RequestMapping(value = "/specification/{specID}",
        produces = { "application/json", "application/xml" }, 
        method = RequestMethod.PUT)
    ResponseEntity<Specification> updateSpec(@Parameter(in = ParameterIn.PATH, description = "specification ID that need to be updated", required=true, schema=@Schema()) @PathVariable("specID") Long specID);

}

