/*
 * Cloud service for robot-vacuum cleaner
 * This is a study project considering server based on the OpenAPI 3.0 specification.  You can now help us improve the API whether it's by making changes to the definition itself or to the code. That way, with time, we can improve the API in general, and expose some of the new features in OAS3.
 *
 * OpenAPI spec version: 0.0.2
 * Contact: kardan97@yandex.ru
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package io.swagger.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.v3.oas.annotations.media.Schema;
import java.io.IOException;
/**
 * Room
 */

@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2022-12-09T12:21:03.478Z[GMT]")
public class Room {
  @SerializedName("id")
  private Long id = null;

  @SerializedName("roomname")
  private String roomname = null;

  @SerializedName("roomsquare")
  private String roomsquare = null;

  public Room id(Long id) {
    this.id = id;
    return this;
  }

   /**
   * Get id
   * @return id
  **/
  @Schema(description = "")
  public Long getId() {
    return id;
  }

  public void setId(Long id) {
    this.id = id;
  }

  public Room roomname(String roomname) {
    this.roomname = roomname;
    return this;
  }

   /**
   * Get roomname
   * @return roomname
  **/
  @Schema(description = "")
  public String getRoomname() {
    return roomname;
  }

  public void setRoomname(String roomname) {
    this.roomname = roomname;
  }

  public Room roomsquare(String roomsquare) {
    this.roomsquare = roomsquare;
    return this;
  }

   /**
   * Get roomsquare
   * @return roomsquare
  **/
  @Schema(description = "")
  public String getRoomsquare() {
    return roomsquare;
  }

  public void setRoomsquare(String roomsquare) {
    this.roomsquare = roomsquare;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    Room room = (Room) o;
    return Objects.equals(this.id, room.id) &&
        Objects.equals(this.roomname, room.roomname) &&
        Objects.equals(this.roomsquare, room.roomsquare);
  }

  @Override
  public int hashCode() {
    return Objects.hash(id, roomname, roomsquare);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class Room {\n");
    
    sb.append("    id: ").append(toIndentedString(id)).append("\n");
    sb.append("    roomname: ").append(toIndentedString(roomname)).append("\n");
    sb.append("    roomsquare: ").append(toIndentedString(roomsquare)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
