/*
 * VDS service
 * This is a study project considering server based on the OpenAPI 3.0 specification.  You can now help us improve the API whether it's by making changes to the definition itself or to the code. That way, with time, we can improve the API in general, and expose some of the new features in OAS3.
 *
 * OpenAPI spec version: 0.0.1
 * Contact: kardan97@yandex.ru
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package io.swagger.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.client.model.Specification;
import io.swagger.client.model.User;
import io.swagger.v3.oas.annotations.media.Schema;
import java.io.IOException;
import org.threeten.bp.OffsetDateTime;
/**
 * Order
 */

@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2022-12-15T15:11:03.787Z[GMT]")
public class Order {
  @SerializedName("id")
  private Long id = null;

  @SerializedName("orderNo")
  private Long orderNo = null;

  @SerializedName("orderDateTime")
  private OffsetDateTime orderDateTime = null;

  @SerializedName("userID")
  private User userID = null;

  @SerializedName("specVDS")
  private Specification specVDS = null;

  @SerializedName("monthsPayed")
  private Integer monthsPayed = null;

  @SerializedName("orderExpiration")
  private String orderExpiration = null;

  public Order id(Long id) {
    this.id = id;
    return this;
  }

   /**
   * Get id
   * @return id
  **/
  @Schema(description = "")
  public Long getId() {
    return id;
  }

  public void setId(Long id) {
    this.id = id;
  }

  public Order orderNo(Long orderNo) {
    this.orderNo = orderNo;
    return this;
  }

   /**
   * Get orderNo
   * @return orderNo
  **/
  @Schema(description = "")
  public Long getOrderNo() {
    return orderNo;
  }

  public void setOrderNo(Long orderNo) {
    this.orderNo = orderNo;
  }

  public Order orderDateTime(OffsetDateTime orderDateTime) {
    this.orderDateTime = orderDateTime;
    return this;
  }

   /**
   * Get orderDateTime
   * @return orderDateTime
  **/
  @Schema(description = "")
  public OffsetDateTime getOrderDateTime() {
    return orderDateTime;
  }

  public void setOrderDateTime(OffsetDateTime orderDateTime) {
    this.orderDateTime = orderDateTime;
  }

  public Order userID(User userID) {
    this.userID = userID;
    return this;
  }

   /**
   * Get userID
   * @return userID
  **/
  @Schema(description = "")
  public User getUserID() {
    return userID;
  }

  public void setUserID(User userID) {
    this.userID = userID;
  }

  public Order specVDS(Specification specVDS) {
    this.specVDS = specVDS;
    return this;
  }

   /**
   * Get specVDS
   * @return specVDS
  **/
  @Schema(description = "")
  public Specification getSpecVDS() {
    return specVDS;
  }

  public void setSpecVDS(Specification specVDS) {
    this.specVDS = specVDS;
  }

  public Order monthsPayed(Integer monthsPayed) {
    this.monthsPayed = monthsPayed;
    return this;
  }

   /**
   * Get monthsPayed
   * @return monthsPayed
  **/
  @Schema(description = "")
  public Integer getMonthsPayed() {
    return monthsPayed;
  }

  public void setMonthsPayed(Integer monthsPayed) {
    this.monthsPayed = monthsPayed;
  }

  public Order orderExpiration(String orderExpiration) {
    this.orderExpiration = orderExpiration;
    return this;
  }

   /**
   * Get orderExpiration
   * @return orderExpiration
  **/
  @Schema(description = "")
  public String getOrderExpiration() {
    return orderExpiration;
  }

  public void setOrderExpiration(String orderExpiration) {
    this.orderExpiration = orderExpiration;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    Order order = (Order) o;
    return Objects.equals(this.id, order.id) &&
        Objects.equals(this.orderNo, order.orderNo) &&
        Objects.equals(this.orderDateTime, order.orderDateTime) &&
        Objects.equals(this.userID, order.userID) &&
        Objects.equals(this.specVDS, order.specVDS) &&
        Objects.equals(this.monthsPayed, order.monthsPayed) &&
        Objects.equals(this.orderExpiration, order.orderExpiration);
  }

  @Override
  public int hashCode() {
    return Objects.hash(id, orderNo, orderDateTime, userID, specVDS, monthsPayed, orderExpiration);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class Order {\n");
    
    sb.append("    id: ").append(toIndentedString(id)).append("\n");
    sb.append("    orderNo: ").append(toIndentedString(orderNo)).append("\n");
    sb.append("    orderDateTime: ").append(toIndentedString(orderDateTime)).append("\n");
    sb.append("    userID: ").append(toIndentedString(userID)).append("\n");
    sb.append("    specVDS: ").append(toIndentedString(specVDS)).append("\n");
    sb.append("    monthsPayed: ").append(toIndentedString(monthsPayed)).append("\n");
    sb.append("    orderExpiration: ").append(toIndentedString(orderExpiration)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
