/*
 * Cloud service for robot-vacuum cleaner
 * This is a study project considering server based on the OpenAPI 3.0 specification.  You can now help us improve the API whether it's by making changes to the definition itself or to the code. That way, with time, we can improve the API in general, and expose some of the new features in OAS3.
 *
 * OpenAPI spec version: 0.0.2
 * Contact: kardan97@yandex.ru
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package io.swagger.client.api;

import io.swagger.client.model.Room;
import org.junit.Test;
import org.junit.Ignore;


import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;


/**
 * API tests for RoomsApi
 */
@Ignore
public class RoomsApiTest {

    private final RoomsApi api = new RoomsApi();

    /**
     * Add a new room
     *
     * Add a new room
     *
     * @throws Exception
     *          if the Api call fails
     */
    @Test
    public void addRoomTest() throws Exception {
        Room body = null;
        Room response = api.addRoom(body);

        // TODO: test validations
    }
    /**
     * Delete room by ID
     *
     * This delete room by ID.
     *
     * @throws Exception
     *          if the Api call fails
     */
    @Test
    public void deleteRoomTest() throws Exception {
        Long roomID = null;
        Room response = api.deleteRoom(roomID);

        // TODO: test validations
    }
    /**
     * Get room by ID
     *
     * Get room by ID
     *
     * @throws Exception
     *          if the Api call fails
     */
    @Test
    public void getRoomTest() throws Exception {
        Long roomID = null;
        Room response = api.getRoom(roomID);

        // TODO: test validations
    }
    /**
     * Update room by ID
     *
     * Update room by ID
     *
     * @throws Exception
     *          if the Api call fails
     */
    @Test
    public void updateRoomTest() throws Exception {
        Long roomID = null;
        Room response = api.updateRoom(roomID);

        // TODO: test validations
    }
}
