/*
 * VDS service
 * This is a study project considering server based on the OpenAPI 3.0 specification.  You can now help us improve the API whether it's by making changes to the definition itself or to the code. That way, with time, we can improve the API in general, and expose some of the new features in OAS3.
 *
 * OpenAPI spec version: 0.0.1
 * Contact: kardan97@yandex.ru
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package io.swagger.client.api;

import org.threeten.bp.OffsetDateTime;
import io.swagger.client.model.Order;
import io.swagger.client.model.Specification;
import io.swagger.client.model.User;
import org.junit.Test;
import org.junit.Ignore;


import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;


/**
 * API tests for OrderApi
 */
@Ignore
public class OrderApiTest {

    private final OrderApi api = new OrderApi();

    /**
     * Create a new order
     *
     * Create a new order
     *
     * @throws Exception
     *          if the Api call fails
     */
    @Test
    public void createOrderTest() throws Exception {
        Order body = null;
        String userID = null;
        String osName = null;
        String osVersion = null;
        String procName = null;
        Integer procCores = null;
        Integer procFreq = null;
        Integer ram = null;
        String diskType = null;
        Integer diskVolume = null;
        String ipType = null;
        Integer ipQuantity = null;
        Integer months = null;
        Order response = api.createOrder(body, userID, osName, osVersion, procName, procCores, procFreq, ram, diskType, diskVolume, ipType, ipQuantity, months);

        // TODO: test validations
    }
    /**
     * Delete an order by ID
     *
     * delete an order by ID
     *
     * @throws Exception
     *          if the Api call fails
     */
    @Test
    public void deleteOrderTest() throws Exception {
        Long orderId = null;
        Order response = api.deleteOrder(orderId);

        // TODO: test validations
    }
    /**
     * Get order by ID
     *
     * Get order by ID
     *
     * @throws Exception
     *          if the Api call fails
     */
    @Test
    public void getOrderTest() throws Exception {
        Long orderId = null;
        Order response = api.getOrder(orderId);

        // TODO: test validations
    }
    /**
     * Update info about an existing order by Id
     *
     * Update info about an existing order by Id
     *
     * @throws Exception
     *          if the Api call fails
     */
    @Test
    public void updateOrderTest() throws Exception {
        Order body = null;
        Long orderId = null;
        Order response = api.updateOrder(body, orderId);

        // TODO: test validations
    }
}
