/*
 * VDS service
 * This is a study project considering server based on the OpenAPI 3.0 specification.  You can now help us improve the API whether it's by making changes to the definition itself or to the code. That way, with time, we can improve the API in general, and expose some of the new features in OAS3.
 *
 * OpenAPI spec version: 0.0.1
 * Contact: kardan97@yandex.ru
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package io.swagger.client.api;

import io.swagger.client.model.Specification;
import org.junit.Test;
import org.junit.Ignore;


import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;


/**
 * API tests for VdsSpecificationApi
 */
@Ignore
public class VdsSpecificationApiTest {

    private final VdsSpecificationApi api = new VdsSpecificationApi();

    /**
     * Delete specification by ID
     *
     * This delete specification by ID.
     *
     * @throws Exception
     *          if the Api call fails
     */
    @Test
    public void deleteSpecTest() throws Exception {
        Long specID = null;
        Specification response = api.deleteSpec(specID);

        // TODO: test validations
    }
    /**
     * Get all VDS specifications info
     *
     * Get all VDS specifications info
     *
     * @throws Exception
     *          if the Api call fails
     */
    @Test
    public void getAllVDSTest() throws Exception {
        List<Specification> response = api.getAllVDS();

        // TODO: test validations
    }
    /**
     * Get VDS specification info by ID
     *
     * Get VDS specification info by ID
     *
     * @throws Exception
     *          if the Api call fails
     */
    @Test
    public void getSpecTest() throws Exception {
        Long specID = null;
        Specification response = api.getSpec(specID);

        // TODO: test validations
    }
    /**
     * Update VDS specification info by ID
     *
     * Update VDS specification info by ID
     *
     * @throws Exception
     *          if the Api call fails
     */
    @Test
    public void updateSpecTest() throws Exception {
        Long specID = null;
        Specification response = api.updateSpec(specID);

        // TODO: test validations
    }
}
